# Generated by Django 5.0.2 on 2024-03-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.PositiveBigIntegerField(db_column='userID')),
            ],
            options={
                'db_table': 'postFollowers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('postID', models.AutoField(db_column='postID', primary_key=True, serialize=False)),
                ('userID', models.PositiveBigIntegerField(db_column='userID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=10000)),
                ('pictureUrl', models.CharField(blank=True, db_column='pictureURL', max_length=255, null=True)),
                ('viewCount', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('reports', models.IntegerField(default=0)),
                ('anonymous', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
    ]
