# Generated by Django 5.0.2 on 2024-03-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.PositiveBigIntegerField(db_column='userID')),
            ],
            options={
                'db_table': 'commentFollowers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentID', models.AutoField(db_column='commentID', primary_key=True, serialize=False)),
                ('userID', models.PositiveBigIntegerField(db_column='userID')),
                ('content', models.TextField(max_length=2000)),
                ('parentCommentID', models.IntegerField(blank=True, db_column='parentCommentID', null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('likes', models.IntegerField(default=0)),
                ('reports', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
    ]
