# Generated by Django 5.0.2 on 2024-03-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardCreationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.PositiveBigIntegerField(db_column='userID')),
                ('fieldName', models.CharField(db_column='fieldName', max_length=255)),
                ('jobName', models.CharField(db_column='jobName', max_length=255)),
                ('boardName', models.CharField(db_column='boardName', max_length=30)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'boardCreationRequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.PositiveBigIntegerField(db_column='userID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'boardFollowers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('boardID', models.AutoField(db_column='boardID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'boards',
                'managed': False,
            },
        ),
    ]
